AWSTemplateFormatVersion: 2010-09-09 

Parameters:
  EC2InstanceType:
    Type: String
  EC2AMI:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  CodePipelineBucket:
    Type: String
    Description: 'The S3 bucket for CodePipeline artefacts'

Resources:

# SecurityGroup acts as Firewall
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      # !Sub function for string interpolation '${}'
      # AWS::StackName - a pseudo parameter
      GroupDescription: !Sub 'Internal Security group for ${AWS::StackName}' 

      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080 
          ToPort: 8080 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp 
          FromPort: 22 
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: Name
          # !Ref function for referencing other resources within stack 
          Value: !Ref AWS::StackName 

# IAM Role which EC2 instance will use to define permissions
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17" 
        Statement:
          Effect: Allow
          Principal:
            Service:
            - "ec2.amazonaws.com"
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess 
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

# Instance Profile used to tie our IAM role to the EC2 instance
  InstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
      - Ref: InstanceRole

# Define our EC2 instance
  Instance:
    Type: AWS::EC2::Instance 
    CreationPolicy: 
      # CloudFormation waits for signal before marking instance as created
      ResourceSignal:
        Timeout: PT15M
        Count: 1
    Metadata:
      AWS::CloudFormation::Init:
        config: 
          packages: 
            yum: 
              wget: []
              unzip: []
    Properties:
      ImageId: !Ref EC2AMI 
      InstanceType: !Ref EC2InstanceType
      IamInstanceProfile: !Ref InstanceProfile 
      Monitoring: true
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId 
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash -xe

          # send script output to /tmp so we can debug boot failures
          exec > /tmp/userdata.log 2>&1 
          
          # Update all packages
          yum -y update

          # Get latest cfn scripts; https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/best- practices.html#cfninit
          yum install -y aws-cfn-bootstrap

          # Have CloudFormation install any files and packages from the metadata
          /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance

          cat > /tmp/install_script.sh << EOF 
            # START
            echo "Setting up NodeJS Environment"
            curl https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash

            # Dot source the files to ensure that variables are available within the current shell
            . /home/ec2-user/.nvm/nvm.sh 
            . /home/ec2-user/.bashrc

            # Install NVM, NPM, Node.JS 
            nvm alias default v12.7.0 
            nvm install v12.7.0
            nvm use v12.7.0

            # Download latest code, unzip it into /home/ec2-user/app
            wget https://github.com/jmurphyweb/aws-bootstrap/archive/master.zip 
            unzip master.zip
            mv aws-bootstrap-master app

            # Create log directory
            mkdir -p /home/ec2-user/app/logs

            # Run server
            cd app
            npm install
            npm start
          EOF

          chown ec2-user:ec2-user /tmp/install_script.sh && chmod a+x /tmp/install_script.sh
          sleep 1; su - ec2-user -c "/tmp/install_script.sh" 

          # Signal to CloudFormation that the instance is ready
          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --region ${AWS::Region} --resource Instance 

      Tags:
        - Key: Name
          Value: !Ref AWS::StackName

# New managed policy to allow EC2 instance to access CodeDeploy
  InstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17" 
        Statement:
          Effect: Allow
          Principal:
            Service:
              - "ec2.amazonaws.com"
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy 
      Tags:
        - Key: Name
        Value: !Ref AWS::StackName

# New IAM role to allow CodeBuild CodeDeploy CodePipeline to access our AWS resources
  DeploymentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument: 
        Version: "2012-10-17" 
        Statement:
          Effect: Allow
          Principal:
            Service:
              - codepipeline.amazonaws.com 
              - codedeploy.amazonaws.com
              - codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/PowerUserAccess

# Define CodeBuild project
  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref AWS::StackName
      ServiceRole: !GetAtt DeploymentRole.Arn 
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER 
        ComputeType: BUILD_GENERAL1_SMALL 
        Image: aws/codebuild/standard:2.0
      Source:
        Type: CODEPIPELINE

# Define CodeDeploy application - lets CodeDeploy know our deployment target is EC2
  DeploymentApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref AWS::StackName 
      ComputePlatform: Server 

# CodeDeploy needs a DeploymentGroup
  StagingDeploymentGroup:
     Type: AWS::CodeDeploy::DeploymentGroup
     DependsOn: Instance
     Properties:
DeploymentGroupName: staging
ApplicationName: !Ref DeploymentApplication DeploymentConfigName: CodeDeployDefault.AllAtOnce ❶ ServiceRoleArn: !GetAtt DeploymentRole.Arn Ec2TagFilters: ❷
- Key: aws:cloudformation:stack-name Type: KEY_AND_VALUE
Value: !Ref AWS::StackName

Outputs:
  InstanceEndpoint:
    Description: The DNS name for the created instance 
    Value: !Sub "http://${Instance.PublicDnsName}:8080" 
    Export:
      Name: InstanceEndpoint